on: [push]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - name: test custom docker action
      id: test-custom-docker-action
      uses: MarkTurney/d-checkout@v1.0.23
    - run: ls -all ~
